on: push

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: InTheWorks-ca/pyinstaller@v1
        with:
          python_ver: '3.6'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'ly2video.exe'
          options: --onefile, --console
