name: Package exe with PyInstaller - Windows

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: ly2video

    - uses: actions/upload-artifact@v2
      with:
        name: ly2video.exe
        path:  # or path/to/artifact
