name: Build

on: workflow_dispatch
      
jobs:
  pyinstaller-build:
    runs-on: <windows-latest / ubuntu-latest >
    steps:
      - name: PyInstaller Action
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          python_ver: '3.6'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'ly2video'
          options: --onefile, --name "ly2video", --console, 
